export default [
    'analise do comportamento',
    'ansiedade',
    'autoconhecimento',
    'autoestima',
    'bem estar',
    'clínica',
    'consciência de si mesmo',
    'Dicas de psicólogas',
    'Dicas de Terapia',
    'dor',
    'escolhas',
    'escolhas adultas',
    'fim de namoro',
    'fim de relacionamento',
    'mães e a pressão social',
    'maternidade e ansiedade',
    'medo',
    'mudança',
    'não ser mãe',
    'Necessidade de aceitação',
    'ninho vázio',
    'Psicóloga',
    'psicologia',
    'psicoterapia',
    'psicoterapia existencial',
    'psicoterapiaparaque',
    'qualidade de vida',
    'relacionamento',
    'Relacionamento na maturidade',
    'responsabilidade',
    'saúde',
    'saúde emocional',
    'saúde mental',
    'segundo filho',
    'Ser mãe',
    'Síndrome do ninho vazio',
    'término',
    'Viver melhor'
]